### ISSUE TITLE
Schemes of fruits, vegetables and tools

### ISSUE THREAD

**Issue by MicheleSpecchia** [AusterweilLab/snafu-py#7]
Where i can find schemes of fruits, vegetables and tools?

**Comment by jeffzemla** [comment]
Hi Michele,

There is an extensive scheme for animals in the github repo, and a less
extensive one for foods. We encourage you to make your own scheme for other
categories and you can use the animal scheme as an example: each scheme is
a two-column csv, where the first column is a subcategory and the second
column is a category. If a member belongs to multiple subcategories, you
can specify that with multiple line entries.

Best,
Jeff
